#RPI_USE_U_BOOT = "1"
ENABLE_UART = "1"
BOOT_DELAY = "0"
BOOT_DELAY_MS = "0"
DISABLE_SPLASH = "1"
GPU_FREQ = "250"
DISABLE_VC4GRAPHICS = "1"
ENABLE_I2C = "1"

CMDLINE:append = " loglevel=7 rw"

RPI_KERNEL_DEVICETREE += " \
    broadcom/bcm2711-rpi-4-b.dtb \
    broadcom/bcm2711-rpi-400.dtb \
    broadcom/bcm2711-rpi-cm4.dtb \
"

MACHINE_EXTRA_RRECOMMENDS += "\
    rpi-config \
    rpi-eeprom \
    u-boot-env \
"

IMAGE_BOOT_FILES += "${KERNEL_IMAGETYPE}-${INITRAMFS_LINK_NAME}.bin;${SDIMG_KERNELIMAGE}"

WKS_FILES = "satobox.wks"
