RPI_KERNEL_DEVICETREE_OVERLAYS:append = " overlays/bcm2712d0.dtbo"
ENABLE_UART = "1"
RPI_EXTRA_CONFIG = ' \n \
# Enable PCIe/NVMe \n \
dtparam=pciex1_gen=3 \n \
# Enable Uart \n \
dtparam=uart0_console \n \
'

CMDLINE:append = " console=ttyAMA0,115200 loglevel=7 rw"

MACHINE_EXTRA_RRECOMMENDS += "\
    rpi-config \
    rpi-eeprom \
    u-boot-env \
"

IMAGE_BOOT_FILES += "${KERNEL_IMAGETYPE}-${INITRAMFS_LINK_NAME}.bin;${SDIMG_KERNELIMAGE}"


WKS_FILES = "satobox.wks"
