# Allow overriding the default machine configuration from meta-raspberrypi
INITRAMFS_IMAGE_BUNDLE = "0"
INITRAMFS_IMAGE = ""

RPI_KERNEL_DEVICETREE_OVERLAYS:append = " overlays/bcm2712d0.dtbo"

RPI_EXTRA_CONFIG = ' \n \
# Enable PCIe/NVMe \n \
dtparam=pciex1_gen=3 \n \
'

CMDLINE:append = " loglevel=7 rw"

MACHINE_EXTRA_RRECOMMENDS += "\
    rpi-config u-boot-env \
"

IMAGE_BOOT_FILES += "${KERNEL_IMAGETYPE};${SDIMG_KERNELIMAGE}"


WKS_FILES = "satobox.wks"
