alias ll="ls -alh"
alias start="systemctl --no-block start"
alias stop="systemctl --no-block stop"
alias restart="systemctl --no-block restart"
alias enable="systemctl enable"
alias disable="systemctl disable"
alias status="systemctl status -l --no-pager"
alias failed="systemctl --failed --no-pager"
alias reload="systemctl daemon-reload"
alias journalctl="journalctl --no-pager"
alias mountrw="mount -o,rw,remount /"
alias mountro="mount -o,ro,remount /"
alias iptables-stop="iptables -P INPUT ACCEPT; iptables -P FORWARD ACCEPT; iptables -P OUTPUT ACCEPT; iptables -F; iptables -X"
alias ip6tables-stop="ip6tables -P INPUT ACCEPT; ip6tables -P FORWARD ACCEPT; ip6tables -P OUTPUT ACCEPT; ip6tables -F; ip6tables -X"
alias bitcoin-cli="bitcoin-cli -conf=/etc/bitcoin/bitcoin.conf"
