# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "satobox"
BBFILE_PATTERN_satobox := "^${LAYERDIR}/"
BBFILE_PRIORITY_satobox = "6"
LAYERSERIES_COMPAT_satobox = "scarthgap"
LAYERDEPENDS_satobox = "core openembedded-layer clang-layer raspberrypi tor integrity security"
SATOBOX_BASE := '${LAYERDIR}'
