# USBGuard rules configuration file
# Allow Trezor wallets
allow id 534c:0001
allow id 1209:53c1
allow id 1209:53c1
allow id 1209:53c1
# Allow bitbox02 wallet
allow id 03eb:2403
# Allow Jade wallets
allow id 10c4:ea60
allow id 1a86:55d4
# Allow Coldcard wallet
allow id d13e:cc10
# Allow KeepKey wallet
allow id 2b24:0001
allow id 2b24:0002
# Allow Digital Bitbox wallet
allow id 03eb:2402
# Allow HW1 Ledger wallet
allow id 2581:1b7c
allow id 2c97:2b7c
allow id 2c97:3b7c
allow id 2c97:4b7c
