############################################
# satobox distro Layer configuration
############################################

#include and overwrite default poky distro
include conf/distro/poky.conf
DISTRO = "satobox"
DISTRO_NAME = "satobox Linux"
INHERIT += "satobox-version"
DISTRO_VERSION := "${SATOBOX_DISTRO_VERSION}"
DISTRO_CODENAME = "Genesis"

IMAGE_VERSION_SUFFIX = "_${DISTRO_VERSION}"

SDK_VERSION="${DISTRO_VERSION}"

MAINTAINER = "Embetrix <ayoub.zaki@embetrix.com>"

TARGET_VENDOR = "-satobox"

# Override these in poky based distros
SATOBOX_DEFAULT_DISTRO_FEATURES = "systemd usrmerge acl xattr zeroconf security integrity"
SATOBOX_DEFAULT_EXTRA_RDEPENDS = "packagegroup-core-boot"
SATOBOX_DEFAULT_EXTRA_RRECOMMENDS = "kernel-module-af-packet"

DISTRO_EXTRA_RDEPENDS += " ${SATOBOX_DEFAULT_EXTRA_RDEPENDS}"
DISTRO_EXTRA_RRECOMMENDS += " ${SATOBOX_DEFAULT_EXTRA_RRECOMMENDS}"

DISTRO_FEATURES:append = " ${SATOBOX_DEFAULT_DISTRO_FEATURES}"
DISTRO_FEATURES:remove = " alsa irda pcmcia nfc nfs 3g debuginfod bluetooth multiarch opengl pulseaudio wayland vulkan x11 ptest"

# Use systemd as init manager
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""
VIRTUAL-RUNTIME_syslog = ""
VIRTUAL-RUNTIME_login_manager = "shadow-base"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"

# Default u-boot-fw-utils
PREFERRED_PROVIDER_u-boot-fw-utils = "libubootenv"

# Overwrite machine config
include conf/machine/${MACHINE}-extra.conf

# default bitcoin rpc credentials
BITCOIND_RPC_USER   ?= "_rpcuser_"
BITCOIND_RPC_PASSWD ?= "_rpcpasswd_"

# Use custom image link
IMAGE_CHAIN_SUFFIX = "${@bb.utils.contains('DISTRO_FEATURES', 'mainnet', '-mainnet', '-signet', d)}"
IMAGE_NAME = "${IMAGE_BASENAME}${IMAGE_CHAIN_SUFFIX}-${MACHINE}${IMAGE_VERSION_SUFFIX}"
IMAGE_LINK_NAME = "${IMAGE_BASENAME}"

# Ship a kernel with bundled initramfs
INITRAMFS_IMAGE  = "satobox-image-initramfs"
INITRAMFS_IMAGE_NAME = "${INITRAMFS_IMAGE}"
INITRAMFS_LINK_NAME = "${MACHINE}"
INITRAMFS_IMAGE_BUNDLE = "1"

LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"

SDKMACHINE = "x86_64"

CLANGSDK = "1"

TOOLCHAIN_HOST_TASK:append = " nativesdk-libclang"

PACKAGE_CLASSES = "package_deb"

INHERIT += "rm_work"
