pid=/var/run/bitcoind.pid
debuglogfile=/var/run/bitcoin/bitcoind.log
datadir=/var/bitcoin
loglevel=info
proxy=127.0.0.1:9050
testnet4=1

# Settings for reduced RAM/CPU/Storage
#dbcache=350
#maxmempool=200
#maxconnections=75
#prune=750

[testnet4]
walletdir=/var/wallet
