RPI_KERNEL_DEVICETREE_OVERLAYS:append = " overlays/bcm2712d0.dtbo"
ENABLE_UART = "1"
RPI_USE_U_BOOT = "1"
RPI_EXTRA_CONFIG = ' \n \
# Enable PCIe/NVMe \n \
dtparam=pciex1_gen=3 \n \
# Enable Uart \n \
dtparam=uart0_console \n \
# Enable Watchdog \n \
dtparam=watchdog=on \n \
'
CMDLINE:append = " console=ttyAMA0,115200 loglevel=7 rw"
#CMDLINE:append = " console=ttyAMA10,115200 earlycon=pl011,0x107d001000,115200n8 loglevel=7 rw"

CMDLINE_ROOT_PARTITION = "/dev/mmcblk0p4"

MACHINE_EXTRA_RRECOMMENDS += "\
    rpi-config \
    rpi-eeprom \
    u-boot-env \
    u-boot-fw-utils \
"

KERNEL_CLASSES  += "kernel-fitimage"
KERNEL_IMAGETYPES += "fitImage"
KERNEL_IMAGETYPE_UBOOT = "fitImage"
KERNEL_BOOTCMD = "bootm"

UBOOT_LOADADDRESS = "0x01080000"
UBOOT_ENTRYPOINT  = "0x01080000"

# do not include fitImage in IMAGE_BOOT_FILES
IMAGE_BOOT_FILES:remove = " fitImage"

IMAGE_FSTYPES += "wic ext4.gz"
WKS_FILES = "satobox.wks"
