#
# raspberrypi5 machine extra configuration
#

ENABLE_UART = "1"
RPI_USE_U_BOOT = "1"
RPI_EXTRA_CONFIG = ' \n \
# Enable PCIe/NVMe \n \
dtparam=pciex1_gen=3 \n \
# Enable Uart \n \
dtparam=uart0_console \n \
# Enable Watchdog \n \
dtparam=watchdog=on \n \
'

CMDLINE:append = " console=ttyAMA0,115200 loglevel=7 ro"
#CMDLINE:append = " console=ttyAMA10,115200 earlycon=pl011,0x107d001000,115200n8 loglevel=7 rw"

#CMDLINE_ROOT_PARTITION = "/dev/mmcblk0p4"
CMDLINE_ROOTFS = "rootwait"

MACHINE_EXTRA_RRECOMMENDS += "\
    rpi-config \
    rpi-eeprom \
    raspi-utils \
    u-boot-env \
    u-boot-fw-utils \
"

# RPI Secure boot settings
RPI_SECBOOT_SIGN = "1"
RPI_SECBOOT_KEY_DIR = "${SATOBOX_BASE}/conf/keys/devel/secure-boot"
RPI_SECBOOT_SIGN_KEY = "${RPI_SECBOOT_KEY_DIR}/secure-boot-sign.key"

# Module signing settings
MODSIGN_KEY_DIR = "${SATOBOX_BASE}/conf/keys/devel/kmod"
MODSIGN_PRIVKEY = "${MODSIGN_KEY_DIR}/kmod-sign.key"
MODSIGN_X509    = "${MODSIGN_KEY_DIR}/kmod-sign.crt"

# Enable FIT image support
KERNEL_CLASSES  += "kernel-fitimage"
KERNEL_IMAGETYPES += "fitImage"
KERNEL_IMAGETYPE_UBOOT = "fitImage"
KERNEL_BOOTCMD = "bootm"

UBOOT_LOADADDRESS = "0x01080000"
UBOOT_ENTRYPOINT  = "0x01080000"

# U-Boot FIT image sign settings
UBOOT_SIGN_ENABLE = "1"
UBOOT_SIGN_KEYDIR = "${SATOBOX_BASE}/conf/keys/devel/fitimage"
UBOOT_SIGN_KEYNAME = "fitimage-sign"


# IMA/EVM settings
IMAGE_CLASSES:append = " ima-evm-rootfs"
IMA_EVM_KEYDIR  = "${SATOBOX_BASE}/conf/keys/devel/ima-evm"
IMA_EVM_PRIVKEY = "${IMA_EVM_KEYDIR}/ima-evm.key"
IMA_EVM_X509    = "${IMA_EVM_KEYDIR}/ima-evm.der"

# Exclude fitImage from IMAGE_BOOT_FILES
IMAGE_BOOT_FILES:remove = " fitImage"

# Exclude fitImage from boot.img
SECBOOT_FILES_EXCLUDE = " fitImage"

# include boot.img and its signature in IMAGE_BOOT_FILES
IMAGE_BOOT_FILES:append = " boot.img boot.sig"
IMAGE_CLASSES:append = " rpi-secboot"
IMAGE_FSTYPES += "rpi-secboot ext4.gz"
IMAGE_FSTYPES:remove = " ext3"

WKS_FILES = "satobox.wks"
