name: CI

permissions:
  contents: write

env:
  MACHINE: raspberrypi5

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false
          ref: ${{ github.ref }}
          fetch-depth: 0
          fetch-tags: true

      - name: Build Testnet Image
        run: KAS_MACHINE=${{env.MACHINE}} kas-container build kas-satobox.yml

      - name: Build Mainnet Image
        run:  KAS_MACHINE=${{env.MACHINE}} kas-container --runtime-args "-e BTC_CHAIN=mainnet" build kas-satobox.yml
        
      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ${{github.workspace}}/build/tmp/deploy/images/${{env.MACHINE}}//satobox-image-signet-${{env.MACHINE}}_*.{manifest,wic.bz2,wic.bmap}

      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/tmp/deploy/images/${{env.MACHINE}}/satobox-image-signet-${{env.MACHINE}}_*.manifest
            build/tmp/deploy/images/${{env.MACHINE}}/satobox-image-mainnet-${{env.MACHINE}}_*.manifest
            build/tmp/deploy/images/${{env.MACHINE}}/satobox-image-signet-${{env.MACHINE}}_*.wic.bz2
            build/tmp/deploy/images/${{env.MACHINE}}/satobox-image-mainnet-${{env.MACHINE}}_*.wic.bz2
            build/tmp/deploy/images/${{env.MACHINE}}/satobox-image-signet-${{env.MACHINE}}_*.wic.bmap
            build/tmp/deploy/images/${{env.MACHINE}}/satobox-image-mainnet-${{env.MACHINE}}_*.wic.bmap
